import vtk
from vtk.util.misc import vtkGetDataRoot
# VTK_DATA_ROOT = vtkGetDataRoot()
VTK_DATA_ROOT = "D:/Library/VTKData"

def main():
    pl3d = vtk.vtkMultiBlockPLOT3DReader()
    pl3d.SetXYZFileName(VTK_DATA_ROOT + "/Data/combxyz.bin")
    pl3d.SetQFileName(VTK_DATA_ROOT + "/Data/combq.bin")
    pl3d.SetScalarFunctionNumber(100)
    pl3d.SetVectorFunctionNumber(202)
    pl3d.Update()
    pl3d_output = pl3d.GetOutput().GetBlock(0)

    line = vtk.vtkLineSource()
    line.SetResolution(30)

    transL1 = vtk.vtkTransform()
    transL1.Translate(3.7, 0.0, 28.37)
    transL1.Scale(5, 5, 5)
    transL1.RotateY(90)
    tf = vtk.vtkTransformPolyDataFilter()
    tf.SetInputConnection(line.GetOutputPort())
    tf.SetTransform(transL1)
    probe = vtk.vtkProbeFilter()
    probe.SetInputConnection(tf.GetOutputPort())
    probe.SetSourceData(pl3d_output)

    transL2 = vtk.vtkTransform()
    transL2.Translate(9.2, 0.0, 31.20)
    transL2.Scale(5, 5, 5)
    transL2.RotateY(90)
    tf2 = vtk.vtkTransformPolyDataFilter()
    tf2.SetInputConnection(line.GetOutputPort())
    tf2.SetTransform(transL2)
    probe2 = vtk.vtkProbeFilter()
    probe2.SetInputConnection(tf2.GetOutputPort())
    probe2.SetSourceData(pl3d_output)

    transL3 = vtk.vtkTransform()
    transL3.Translate(13.27, 0.0, 33.40)
    transL3.Scale(4.5, 4.5, 4.5)
    transL3.RotateY(90)
    tf3 = vtk.vtkTransformPolyDataFilter()
    tf3.SetInputConnection(line.GetOutputPort())
    tf3.SetTransform(transL3)
    probe3 = vtk.vtkProbeFilter()
    probe3.SetInputConnection(tf3.GetOutputPort())
    probe3.SetSourceData(pl3d_output)

    appendF = vtk.vtkAppendPolyData()
    appendF.AddInputConnection(probe.GetOutputPort())
    appendF.AddInputConnection(probe2.GetOutputPort())
    appendF.AddInputConnection(probe3.GetOutputPort())

    tuber = vtk.vtkTubeFilter()
    tuber.SetInputConnection(appendF.GetOutputPort())
    tuber.SetRadius(0.1)
    lineMapper = vtk.vtkPolyDataMapper()
    lineMapper.SetInputConnection(tuber.GetOutputPort())
    lineActor = vtk.vtkActor()
    lineActor.SetMapper(lineMapper)

    xyplot = vtk.vtkXYPlotActor()
    xyplot.AddDataSetInputConnection(probe.GetOutputPort())
    xyplot.AddDataSetInputConnection(probe2.GetOutputPort())
    xyplot.AddDataSetInputConnection(probe3.GetOutputPort())
    xyplot.GetPositionCoordinate().SetValue(0.0, 0.67, 0)
    xyplot.GetPosition2Coordinate().SetValue(1.0, 0.33, 0)
    xyplot.SetXValuesToArcLength()
    xyplot.SetNumberOfXLabels(6)
    xyplot.SetTitle("Pressure vs. Arc Length (Zoomed View)")
    xyplot.SetXTitle("")
    xyplot.SetYTitle("P")
    xyplot.SetXRange(0.1, 0.35)
    xyplot.SetYRange(0.2, 0.4)
    xyplot.GetProperty().SetColor(0, 0, 0)
    xyplot.GetProperty().SetLineWidth(2)
    tprop = xyplot.GetTitleTextProperty()
    tprop.SetColor(xyplot.GetProperty().GetColor())
    xyplot.SetAxisTitleTextProperty(tprop)
    xyplot.SetAxisLabelTextProperty(tprop)

    xyplot2 = vtk.vtkXYPlotActor()
    xyplot2.AddDataSetInputConnection(probe.GetOutputPort())
    xyplot2.AddDataSetInputConnection(probe2.GetOutputPort())
    xyplot2.AddDataSetInputConnection(probe3.GetOutputPort())
    xyplot2.GetPositionCoordinate().SetValue(0.0, 0.33, 0)
    xyplot2.GetPosition2Coordinate().SetValue(1.0, 0.33, 0)
    xyplot2.SetXValuesToArcLength()
    xyplot2.SetNumberOfXLabels(6)
    xyplot2.SetTitle("Pressure vs. Arc Length")
    xyplot2.SetXTitle("")
    xyplot2.SetYTitle("P")
    xyplot2.PlotPointsOn()
    xyplot2.PlotLinesOff()
    xyplot2.GetProperty().SetColor(1, 0, 0)
    xyplot2.GetProperty().SetLineWidth(2)
    tprop = xyplot2.GetTitleTextProperty()
    tprop.SetColor(xyplot2.GetProperty().GetColor())
    xyplot2.SetAxisTitleTextProperty(tprop)
    xyplot2.SetAxisLabelTextProperty(tprop)

    xyplot3 = vtk.vtkXYPlotActor()
    xyplot3.AddDataSetInputConnection(probe.GetOutputPort())
    xyplot3.AddDataSetInputConnection(probe2.GetOutputPort())
    xyplot3.AddDataSetInputConnection(probe3.GetOutputPort())
    xyplot3.GetPositionCoordinate().SetValue(0.0, 0.0, 0)
    xyplot3.GetPosition2Coordinate().SetValue(1.0, 0.33, 0)
    xyplot3.SetXValuesToIndex()
    xyplot3.SetNumberOfXLabels(6)
    xyplot3.SetTitle("Pressure vs. Point Id")
    xyplot3.SetXTitle("Probe Length")
    xyplot3.SetYTitle("P")
    xyplot3.PlotPointsOn()
    xyplot3.GetProperty().SetColor(0, 0, 1)
    xyplot3.GetProperty().SetPointSize(3)
    tprop = xyplot3.GetTitleTextProperty()
    tprop.SetColor(xyplot3.GetProperty().GetColor())
    xyplot3.SetAxisTitleTextProperty(tprop)
    xyplot3.SetAxisLabelTextProperty(tprop)

    outline = vtk.vtkStructuredGridOutlineFilter()
    outline.SetInputData(pl3d_output)
    outlineMapper = vtk.vtkPolyDataMapper()
    outlineMapper.SetInputConnection(outline.GetOutputPort())
    outlineActor = vtk.vtkActor()
    outlineActor.SetMapper(outlineMapper)
    outlineActor.GetProperty().SetColor(0, 0, 0)

    renderer = vtk.vtkRenderer()
    renderer.SetBackground(0.3, 0.5, 0.7)
    renderer.SetViewport(0, 0, 0.5, 1)
    renderer.AddActor(outlineActor)
    renderer.AddActor(lineActor)

    renderer2 = vtk.vtkRenderer()
    renderer2.SetBackground(0.3, 0.5, 0.7)
    renderer2.SetViewport(0.5, 0.0, 1.0, 1.0)
    renderer2.AddActor2D(xyplot)
    renderer2.AddActor2D(xyplot2)
    renderer2.AddActor2D(xyplot3)

    window = vtk.vtkRenderWindow()
    window.AddRenderer(renderer)
    window.AddRenderer(renderer2)
    window.SetSize(500, 250)

    camera = renderer.GetActiveCamera()
    camera.SetClippingRange(3.95297, 100)
    camera.SetFocalPoint(8.88908, 0.595038, 29.3342)
    camera.SetPosition(-12.3332, 31.7479, 41.2387)
    camera.SetViewUp(0.060772, -0.319905, 0.0945498)

    windowInteractor = vtk.vtkRenderWindowInteractor()
    windowInteractor.SetRenderWindow(window)

    window.Render()
    windowInteractor.Start()

if __name__ == "__main__":
    main()
